[package]
name = "state_machines"
version = "0.1.0"
edition = "2024"

[dependencies]
state_machines_core = { path = "../state_machines_core" }
state_machines_macro = { path = "../state_machines_macro" }

[dev-dependencies]
pollster = "0.4"
